### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zfrg** [littlewhitecloud/CustomTkinterTitlebar#47]
每次导入这个库就报错

终端所有输出：
```
D:\Desktop>py app.py
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from customtitlebar import CTT
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\customtitlebar\__init__.py", line 14, in <module>
    from .titlebar import CTT
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\customtitlebar\titlebar.py", line 15, in <module>
    class CTT(Tk):
  File "D:\Program Files (x86)\Python37-32\lib\site-packages\customtitlebar\titlebar.py", line 157, in CTT
    def maximize(self, _: Event | None = None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

望修复！

**Comment by littlewhitecloud** [comment]
这个其实是你的python版本(3.7)过低所以导致不支持这个语法。
请重新从github上下载最新的版本再测试一下。谢谢！

**Comment by littlewhitecloud** [comment]
@zfrg 修复好了吗？
